//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.LibraryGuest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WCFBookLibrary")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRentedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.LibraryGuest.Author _dudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _signatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRented {
            get {
                return this.IsRentedField;
            }
            set {
                if ((this.IsRentedField.Equals(value) != true)) {
                    this.IsRentedField = value;
                    this.RaisePropertyChanged("IsRented");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.LibraryGuest.Author _dude {
            get {
                return this._dudeField;
            }
            set {
                if ((object.ReferenceEquals(this._dudeField, value) != true)) {
                    this._dudeField = value;
                    this.RaisePropertyChanged("_dude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _signature {
            get {
                return this._signatureField;
            }
            set {
                if ((this._signatureField.Equals(value) != true)) {
                    this._signatureField = value;
                    this.RaisePropertyChanged("_signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _title {
            get {
                return this._titleField;
            }
            set {
                if ((object.ReferenceEquals(this._titleField, value) != true)) {
                    this._titleField = value;
                    this.RaisePropertyChanged("_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _year {
            get {
                return this._yearField;
            }
            set {
                if ((this._yearField.Equals(value) != true)) {
                    this._yearField = value;
                    this.RaisePropertyChanged("_year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/WCFBookLibrary")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SingleAuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.LibraryGuest.Author[] _authorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SingleAuthor {
            get {
                return this.SingleAuthorField;
            }
            set {
                if ((this.SingleAuthorField.Equals(value) != true)) {
                    this.SingleAuthorField = value;
                    this.RaisePropertyChanged("SingleAuthor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.LibraryGuest.Author[] _authors {
            get {
                return this._authorsField;
            }
            set {
                if ((object.ReferenceEquals(this._authorsField, value) != true)) {
                    this._authorsField = value;
                    this.RaisePropertyChanged("_authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _surname {
            get {
                return this._surnameField;
            }
            set {
                if ((object.ReferenceEquals(this._surnameField, value) != true)) {
                    this._surnameField = value;
                    this.RaisePropertyChanged("_surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookIsAlreadyRentedFault", Namespace="http://schemas.datacontract.org/2004/07/WCFBookLibrary")]
    [System.SerializableAttribute()]
    public partial class BookIsAlreadyRentedFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoSuchBooksFault", Namespace="http://schemas.datacontract.org/2004/07/WCFBookLibrary")]
    [System.SerializableAttribute()]
    public partial class NoSuchBooksFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryGuest.ILibrary", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetAllBooks", ReplyAction="http://tempuri.org/ILibrary/GetAllBooksResponse")]
        ConsoleApp1.LibraryGuest.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetAllBooks", ReplyAction="http://tempuri.org/ILibrary/GetAllBooksResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetAllRentedBooks", ReplyAction="http://tempuri.org/ILibrary/GetAllRentedBooksResponse")]
        ConsoleApp1.LibraryGuest.Book[] GetAllRentedBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetAllRentedBooks", ReplyAction="http://tempuri.org/ILibrary/GetAllRentedBooksResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book[]> GetAllRentedBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetAllBooksWithTitleLike", ReplyAction="http://tempuri.org/ILibrary/GetAllBooksWithTitleLikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.LibraryGuest.BookIsAlreadyRentedFault), Action="http://tempuri.org/ILibrary/GetAllBooksWithTitleLikeBookIsAlreadyRentedFaultFault" +
            "", Name="BookIsAlreadyRentedFault", Namespace="http://schemas.datacontract.org/2004/07/WCFBookLibrary")]
        ConsoleApp1.LibraryGuest.Book[] GetAllBooksWithTitleLike(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetAllBooksWithTitleLike", ReplyAction="http://tempuri.org/ILibrary/GetAllBooksWithTitleLikeResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book[]> GetAllBooksWithTitleLikeAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/ReturnBook", ReplyAction="http://tempuri.org/ILibrary/ReturnBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.LibraryGuest.NoSuchBooksFault), Action="http://tempuri.org/ILibrary/ReturnBookNoSuchBooksFaultFault", Name="NoSuchBooksFault", Namespace="http://schemas.datacontract.org/2004/07/WCFBookLibrary")]
        void ReturnBook(int signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/ReturnBook", ReplyAction="http://tempuri.org/ILibrary/ReturnBookResponse")]
        System.Threading.Tasks.Task ReturnBookAsync(int signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/RentBook", ReplyAction="http://tempuri.org/ILibrary/RentBookResponse")]
        void RentBook(int signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/RentBook", ReplyAction="http://tempuri.org/ILibrary/RentBookResponse")]
        System.Threading.Tasks.Task RentBookAsync(int signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetBook", ReplyAction="http://tempuri.org/ILibrary/GetBookResponse")]
        ConsoleApp1.LibraryGuest.Book GetBook(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/GetBook", ReplyAction="http://tempuri.org/ILibrary/GetBookResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book> GetBookAsync(int i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryChannel : ConsoleApp1.LibraryGuest.ILibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryClient : System.ServiceModel.ClientBase<ConsoleApp1.LibraryGuest.ILibrary>, ConsoleApp1.LibraryGuest.ILibrary {
        
        public LibraryClient() {
        }
        
        public LibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApp1.LibraryGuest.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public ConsoleApp1.LibraryGuest.Book[] GetAllRentedBooks() {
            return base.Channel.GetAllRentedBooks();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book[]> GetAllRentedBooksAsync() {
            return base.Channel.GetAllRentedBooksAsync();
        }
        
        public ConsoleApp1.LibraryGuest.Book[] GetAllBooksWithTitleLike(string text) {
            return base.Channel.GetAllBooksWithTitleLike(text);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book[]> GetAllBooksWithTitleLikeAsync(string text) {
            return base.Channel.GetAllBooksWithTitleLikeAsync(text);
        }
        
        public void ReturnBook(int signature) {
            base.Channel.ReturnBook(signature);
        }
        
        public System.Threading.Tasks.Task ReturnBookAsync(int signature) {
            return base.Channel.ReturnBookAsync(signature);
        }
        
        public void RentBook(int signature) {
            base.Channel.RentBook(signature);
        }
        
        public System.Threading.Tasks.Task RentBookAsync(int signature) {
            return base.Channel.RentBookAsync(signature);
        }
        
        public ConsoleApp1.LibraryGuest.Book GetBook(int i) {
            return base.Channel.GetBook(i);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.LibraryGuest.Book> GetBookAsync(int i) {
            return base.Channel.GetBookAsync(i);
        }
    }
}
